version: '3.8'

services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dev
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  celery:
    build: .
    command: celery -A conf worker -l info
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A conf beat -l info
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - celery