# Generated by Django 4.2 on 2023-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorereview',
            name='at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
